linters:
  # Disable all linters by default.
  # Default: false
  disable-all: true

  # Enable specific linters
  # https://golangci-lint.run/usage/linters/#enabled-by-default-linters
  enable:
    # Default linters
    - errcheck        # Check for unchecked errors
    - gosimple        # Simplify code
    - govet           # Vet the code
    - ineffassign     # Detect unnecessary assignments
    - staticcheck     # Perform static analysis
    - typecheck       # Check for type errors
    - unused          # Detect unused code

    # Additional linters
    - gosec           # Security-related issues
    - forcetypeassert # Check for forced type assertions
    # - contextcheck   # Disabled in CI for now due to necessary fixes
    - noctx           # Avoid using context.Context directly
    # - unconvert      # Disable because extra conversions can often clarify code
    - unparam         # Detect unused parameters in functions
    - prealloc        # Suggest slice preallocation

issues:
  # Exclude specific rules for certain files
  exclude-rules:
    - path: pkg/supervisor/supervisor_testhelpers.go
      text: "^func.*supervisor.*(waitSettle|waitSettleError).*$"
      linters:
        - unused   # Exclude 'unused' linter for these functions
